#! /bin/bash
# oblerion makedeb 1.1 2022
input=""
str=""
BIN="main"
NDIR=""
file=""

Vpack=""
Vvers=""
Varch=""
Vmaint=""
Vdescr=""

function init_dir()
{
	NDIR=$1
	echo $NDIR
	DDEBIAN="${1}/DEBIAN"
	if [ ! -d $1 ];then 
		mkdir $1
		mkdir -p $1/usr/local/bin
		cp $BIN $1/usr/local/bin/.
		mkdir $1/opt
		mkdir $DDEBIAN
		mkdir ${1}/debian
		touch ${1}/debian/control
		touch $DDEBIAN/control
	fi
}

function init_control()
{
	echo "Package: (def:file_name)" ;
	read input;
	if [ ${#input} -lt 1 ];then
		Vpack="$BIN";
	else
		Vpack=$input;
	fi
	echo "Version: (def:1.0)";
	read input;
	if [ ${#input} -lt 1 ];then 	
		Vvers="1.0"; 
	else
		Vvers=$input;
	fi

	echo "Architecture: (def:amd64)";
	read input;
	if [ ${#input} -lt 1 ];then 
		input="amd64"; 
	fi
	Varch=$input

	echo "Maintainer: exemple -> <name@mail.com>";
	read input;
	Vmaint=$input

	echo "Description:";
	read input;
	Vdescr=$input
}
function write_control()
{
	command echo "Package: ${Vpack}">>$NDIR/DEBIAN/control
	command echo "Version: ${Vvers}">>$NDIR/DEBIAN/control
	command echo "Architecture: ${Varch}">>$NDIR/DEBIAN/control
	command echo "Maintainer: ${Vmaint}">>$NDIR/DEBIAN/control
	command echo "Description: ${Vdescr}">>$NDIR/DEBIAN/control
}
function print_help()
{
	echo "makedeb file";
	echo "--> generate .deb from binairy app"
	echo "makedeb -d file"
	echo "--> generate dir_deb from binairy app"
	echo "makedeb -dex dir_deb"
	echo "--> generate .deb from dir_deb"
}
if [ -f $1 ] && 
[ ! "$1"="-d" ] && 
[ ! "$1"="-dex" ];then
	BIN="$1";
	init_control;
	init_dir "${Vpack}-${Vvers}-${Varch}";
	write_control;
	cd $NDIR
	command dpkg-shlibdeps -e usr/local/bin/$BIN;
	cp debian/substvars DEBIAN/substvars
	rm -r debian
	file=$(< DEBIAN/substvars);
	rm DEBIAN/substvars;
	if [ ! -s $file ];then  
		echo "${file:7:7}: ${file:15}">>DEBIAN/control;
	fi
	cd ..
	command dpkg-deb --build --root-owner-group $NDIR
elif [ "$1"="-d" ] && [ -f $2 ];then
	BIN="$2";
	init_control;
	rm -f -r "${Vpack}-${Vvers}-${Varch}";
	init_dir "${Vpack}-${Vvers}-${Varch}";
	write_control;
	cd $NDIR
	command dpkg-shlibdeps -e usr/local/bin/$BIN;
	cp debian/substvars DEBIAN/substvars
	rm -r debian
	file=$(< DEBIAN/substvars);
	rm DEBIAN/substvars;
	if [ ! -s $file ];then  
		echo "${file:7:7}: ${file:15}">>DEBIAN/control;
	fi
	cd ..
elif [ "$1"="-dex" ] && [ -d $2 ];then
	command dpkg-deb --build --root-owner-group $2;
elif [ "$1"="--help" ] || [ "$1"="help" ];then
	print_help;
else
	echo "first arg isn t file"
fi
